### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ghost** [orweis/winregal#1]
Hi, I have a problem when i tried to import WinRegal with python3.5 on windows 10.

C:\Python34\python.exe E:/Dev/Projets_python/Projets/MAME-pycharm/main.pyw
Traceback (most recent call last):
  File "E:/Dev/Projets_python/Projets/MAME-pycharm/main.pyw", line 29, in <module>
    import winregal
  File "C:\Python34\lib\site-packages\winregal\__init__.py", line 10, in <module>
    from winregal import RegKey, RegValue, WinregalException
ImportError: cannot import name 'RegKey'

Thanks for your help.

Stéphane

**Comment by orweis** [comment]
Just saw your email.
This is a Python 3, issue. Will Fix soon.

**Comment by orweis** [comment]
Issue should be fixed.
Please try pip install winregal --upgrade

**Comment by ghost** [comment]
Thanks for your quick update.
Cheers
Stéphane
